version: '3.9'

services:
    server:
        container_name: mc-server
        build:
            context: .
            dockerfile: dockerfile
        restart: always
        ports:
            - 25565:25565
        volumes:
            - minecraft:/minecraft

volumes:
    minecraft:
        driver: local