services:
    server:
        container_name: mc-server
        build:
            context: .
            dockerfile: dockerfile.alpine
        restart: always
        ports:
            - 25000:25565
        volumes:
            - minecraft:/minecraft
        stdin_open: true
        # tty: true
        deploy:
            resources:
                limits:
                    cpus: '2.00'
                    memory: 2048M

volumes:
    minecraft:
        driver: local